#                                                                
#                                                                
#                                                                
#                                                                
#                                                                
#                                -*                              
#                              @!!!!!                            
#                            +!!!!!!!!.                          
#                           =!!!!!!!!!!.                         
#                           !!!!!!!!!!!+                         
#             :!!!!!!!!!!-  @!!!!!!!!!!.  -!!!!!!!.              
#             -!!!!!!!!!!!!- !!!!!!!!!! !!!!!!!!!!!!!            
#              !!!!!!!!!!!!!: !!!!!!!:.!!!!!!!!!!!!!.            
#              .!!!!!!!!!!!!!         !!!!!!!!!!!!!=             
#                !!!!!!!!!!            !!!!!!!!!!!+              
#                   !!!!!!.             !!!!!!!!*                
#                    .--                                         
#                =!!!!!!!!:             !!!!!!!*                 
#              -!!!!!!!!!!!+           !!!!!!!!!!!               
#             .!!!!!!!!!!!!!-        -!!!!!!!!!!!!!              
#             !!!!!!!!!!!!!+-!!!!!!!! @!!!!!!!!!!!!+             
#             !!!!!!!!!!!@ -!!!!!!!!!! :!!!!!!!!!!!!             
#                .+!@!*    !!!!!!!!!!!-  .!!!!!!!!!.             
#                          !!!!!!!!!!!:                          
#                          +!!!!!!!!!!                           
#                           :!!!!!!!!                            
#                             !!!!!                              
#                                                                
#                                                                
#                                                                
#                                                                
#                                                                
#

#
# elegance: an elegant 16-color skin for MidnightCommander.



[skin]

  description             =   Elegant skin for user
  256colors               =   false



[Lines]

  horiz                   =   ─
  vert                    =   │
  lefttop                 =   ┌
  righttop                =   ┐
  leftbottom              =   └
  rightbottom             =   ┘
  topmiddle               =   ─
  bottommiddle            =   ─
  leftmiddle              =   ├
  rightmiddle             =   ┤
  cross                   =   ┼
  dhoriz                  =   ─
  dvert                   =   │
  dlefttop                =   ┌
  drighttop               =   ┐
  dleftbottom             =   └
  drightbottom            =   ┘
  dtopmiddle              =   ─
  dbottommiddle           =   ─
  dleftmiddle             =   ├
  drightmiddle            =   ┤



[core]
  _default_               =   default;default
  selected                =   ;;bold
  marked                  =   green;;
  markselect              =   green;;bold
  gauge                   =   color15;default
  input                   =   green;default
  inputmark               =   green;default;bold
  inputunchanged          =   green;default
  commandlinemark         =   green;default;bold
  reverse                 =   default;default
  header                  =   green;default;
  disabled                =   default;default
  #inputhistory           =
  #commandhistory         =



[dialog]

  _default_               =   default;default
  dhotnormal              =   default
  dfocus                  =   ;;bold
  dhotfocus               =   ;;bold
  dtitle                  =   ;;bold



[error]

  _default_               =   default;default
  errdhotnormal           =   default
  errdfocus               =   ;;bold
  errdhotfocus            =   ;;bold
  errdtitle               =   ;;bold



[filehighlight]

  directory               =   default
  executable              =   default
  symlink                 =   default
  hardlink                =   default
  stalelink               =   default
  device                  =   lightgray
  special                 =   lightgray
  core                    =   lightgray
  temp                    =   lightgray
  archive                 =   brown
  doc                     =   default
  source                  =   lightgray
  media                   =   yellow
  graph                   =   magenta
  database                =   brown



[menu]

  _default_               =   default;default
  menuhotsel              =   default;default
  menusel                 =   default;default;bold
  menuhotsel              =   default;default;bold
  menuinactive            =   default



[popupmenu]

  _default_               =   default;default
  menusel                 =   ;;bold
  menutitle               =   ;;bold



[buttonbar]

  button                  =   default
  hotkey                  =   green;default



[statusbar]

  _default_               =   color15;default



[help]

  _default_               =   color0;color7
  helpitalic              =   color10;;bold
  helpbold                =   color5
  helplink                =   color14
  helpslink               =   color11;color2;bold



[editor]

  _default_               =   default;default
  editbold                =   color15;;bold
  editmarked              =   default;lightgray;
  editwhitespace          =   color12;color4
  editlinestate           =   color2;color0
  bookmark                =   color0;color7
  bookmarkfound           =   color0;color7
  editrightmargin         =   color0;color7



[viewer]

  _default_               =   default;default
  viewunderline           =   ;;underline



[diffviewer]

  changedline             =   color15;color4
  changednew              =   color15;color2
  changed                 =   color15;color6
  added                   =   color0;color7
  removed                 =   color8;color0
  folder                  =   color11;color0;bold
  error                   =   color15;color1



[widget-common]

  sort-sign-up            =   ↓
  sort-sign-down          =   ↑



[widget-panel]

  hiddenfiles-sign-show   =   .
  hiddenfiles-sign-hide   =   .
  history-prev-item-sign  =   «
  history-next-item-sign  =   »
  history-show-list-sign  =   ^



[widget-scollbar]

  first-vert-char         =   ↑
  last-vert-char          =   ↓
  first-horiz-char        =   «
  last-horiz-char         =   »
  current-char            =   ■
  background-char         =   ▒